//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace myProject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kayit
    {
        public int kayitId { get; set; }
        public int kayitDersId { get; set; }
        public int kayitOgrId { get; set; }
        public int kayitOdevId { get; set; }
        public int kayitAdminId { get; set; }
    
        public virtual Admin Admin { get; set; }
        public virtual Ders Ders { get; set; }
        public virtual Odev Odev { get; set; }
        public virtual Ogrenci Ogrenci { get; set; }
    }
}
